/*
고객 상세정보 dummy data
@author 조혜안
@since 2023.11.26
*/
export default function dummyCsmrDetailInfo() {
  const dummyData = [
    {
      csmrMgmtNo: "MgmtNo1",
      sexCd: "M",
      csmrTymdNo: "1990-01-01",
      telNum: "010-1234-5678",
      tnUsblScnCd: "Y",
      emlAdr: "example@example.com",
      emlUsblScnCd: "Y",
      rdnmAdr: "1234 Street, City",
      rdnmUsblScnCd: "Y",
      wkplNm: "ABC Company",
      opsNm: "Sales Department",
      poaNm: "Manager",
      famTypCd: "Family A",
      mariYn: "Y",
      csmrChtSpsn: "2",
      csmrPreCarCd: "CarX",
      carHldgCnt: "1",
      carChngPrd: "365",
      exrsEeEeno: "Employee001",
      inpEeno: "Inputter001",
      inpDtm: "2023-11-26 10:00:00",
      chgrEeno: "Modifier001",
      altrDtm: "2023-11-26 10:30:00",
    },
    {
      csmrMgmtNo: "MgmtNo1",
      sexCd: "M",
      csmrTymdNo: "1990-01-01",
      telNum: "010-1234-5678",
      tnUsblScnCd: "Y",
      emlAdr: "example@example.com",
      emlUsblScnCd: "Y",
      rdnmAdr: "1234 Street, City",
      rdnmUsblScnCd: "Y",
      wkplNm: "ABC Company",
      opsNm: "Sales Department",
      poaNm: "Manager",
      famTypCd: "Family A",
      mariYn: "Y",
      csmrChtSpsn: "2",
      csmrPreCarCd: "CarX",
      carHldgCnt: "1",
      carChngPrd: "365",
      exrsEeEeno: "Employee001",
      inpEeno: "Inputter001",
      inpDtm: "2023-11-26 10:00:00",
      chgrEeno: "Modifier001",
      altrDtm: "2023-11-26 10:30:00",
    },
    {
      csmrMgmtNo: "MgmtNo1",
      sexCd: "M",
      csmrTymdNo: "1990-01-01",
      telNum: "010-1234-5678",
      tnUsblScnCd: "Y",
      emlAdr: "example@example.com",
      emlUsblScnCd: "Y",
      rdnmAdr: "1234 Street, City",
      rdnmUsblScnCd: "Y",
      wkplNm: "ABC Company",
      opsNm: "Sales Department",
      poaNm: "Manager",
      famTypCd: "Family A",
      mariYn: "Y",
      csmrChtSpsn: "2",
      csmrPreCarCd: "CarX",
      carHldgCnt: "1",
      carChngPrd: "365",
      exrsEeEeno: "Employee001",
      inpEeno: "Inputter001",
      inpDtm: "2023-11-26 10:00:00",
      chgrEeno: "Modifier001",
      altrDtm: "2023-11-26 10:30:00",
    },
    {
      csmrMgmtNo: "MgmtNo1",
      sexCd: "M",
      csmrTymdNo: "1990-01-01",
      telNum: "010-1234-5678",
      tnUsblScnCd: "Y",
      emlAdr: "example@example.com",
      emlUsblScnCd: "Y",
      rdnmAdr: "1234 Street, City",
      rdnmUsblScnCd: "Y",
      wkplNm: "ABC Company",
      opsNm: "Sales Department",
      poaNm: "Manager",
      famTypCd: "Family A",
      mariYn: "Y",
      csmrChtSpsn: "2",
      csmrPreCarCd: "CarX",
      carHldgCnt: "1",
      carChngPrd: "365",
      exrsEeEeno: "Employee001",
      inpEeno: "Inputter001",
      inpDtm: "2023-11-26 10:00:00",
      chgrEeno: "Modifier001",
      altrDtm: "2023-11-26 10:30:00",
    }
  ];

  return dummyData;
}

